In [1]:
%config Completer.use_jedi = False

In [ ]:
test_list = [[1,2,3,4], [1,2,], [1,2,3,4,5,6,7,8]]

longest_sent = len(max(test_list))
outlist = []

for sent in test_list:
    outlist.append(sent + [item for item in ["*"]*(longest_sent-len(sent))])
    
outlist

In [ ]:
test_list

In [ ]:
sents = [[1,2,3,4], [1,2,], [1,2,3,4,5,6,7,8]]
pad_token = "*"

sents_padded = []

### YOUR CODE HERE (~6 Lines)
corpus_size = len(sents)
lens = [len(i) for i in sents] # cache it for later use
max_lens = max(lens)
sents_padded = [sents[i] + [pad_token] * (max_lens - lens[i]) for i in range(corpus_size)] # shape N x max_lens

In [ ]:
sents_padded

In [ ]:
outlist == sents_padded

In [ ]:
import torch

In [ ]:
x = torch.randn(2, 4, 3)
print(x)
torch.cat((x[0], x[1]), 1)

In [ ]:
print(x.size())
print(x.unsqueeze(0).size())
print(x.unsqueeze(1).size())
print(x.unsqueeze(2).size())
print(x.unsqueeze(3).size())
print(x.unsqueeze(0).squeeze(0).size())
print(x.unsqueeze(1).squeeze(0).size())
print(x.unsqueeze(2).squeeze(1).size())
print(x.unsqueeze(3).squeeze(0).size())

In [ ]:
x

In [ ]:
x.sum(dim=0)

In [ ]:
x.sum(dim=1)

In [ ]:
x.sum(dim=2)

In [ ]:
torch.squeeze(x)

In [ ]:
torch.nn.functional.softmax(x, dim=2)

In [ ]:
y = torch.randn(2,3,4)
y

In [ ]:
torch.bmm(x,y).size()

In [2]:
import torch

In [12]:
batch_size = 16
word_embed_size = 4
seq_len = 7
input_ = torch.randn(batch_size, word_embed_size, seq_len)
conv1 = torch.nn.Conv1d(in_channels=word_embed_size, out_channels=3, kernel_size=3, padding=1)
hidden1 = conv1(input_)
hidden2 = torch.max(hidden1, dim=2)

In [14]:
input_

tensor([[[ 1.4444e+00, -3.3771e-01, -4.0921e-01,  6.6343e-01, -9.1910e-01,
          -1.1290e+00,  5.1472e-02],
         [-3.5460e-01,  3.3954e-01,  5.3805e-02,  6.4034e-01,  3.9350e-01,
          -4.0110e-01,  1.9090e+00],
         [-1.1473e+00, -1.0372e+00, -6.0801e-01,  1.2321e+00, -2.4419e-02,
           2.4545e+00,  8.5942e-01],
         [-1.1304e+00, -7.6990e-01, -8.2454e-01,  2.4008e+00, -2.0976e-02,
           2.2536e-01, -5.7391e-01]],

        [[-5.5962e-01,  9.9780e-01,  1.6617e-01,  2.4147e-02, -8.6084e-02,
          -6.1057e-01, -1.0902e+00],
         [-9.1170e-02,  8.0097e-01, -8.1760e-02,  3.0874e-01,  1.0323e+00,
          -1.8400e-01, -1.1630e+00],
         [-1.4224e+00,  6.4243e-01,  6.5999e-01, -2.1980e-01, -4.3127e-01,
           1.7270e-01, -1.2345e+00],
         [ 2.4748e+00, -1.0098e+00, -8.2709e-03,  2.5039e-01, -2.3432e-01,
           1.0961e+00, -1.4834e+00]],

        [[-1.3601e-01, -1.9729e+00, -4.0499e-01, -1.2132e+00,  2.5676e-01,
          -5.7585e-01,  1

In [15]:
hidden1

tensor([[[-5.6019e-02,  2.8375e-01, -4.9572e-01,  2.5541e-01,  3.8673e-02,
          -7.9294e-01, -8.3053e-01],
         [-9.4289e-02, -3.7549e-01, -6.7371e-01, -5.3224e-01,  7.2856e-02,
           2.5861e-01, -7.7753e-01],
         [-1.0717e-01, -5.7513e-01, -3.1966e-01, -6.3601e-01,  6.6318e-01,
          -5.0265e-01, -2.6270e-01]],

        [[ 2.5544e-01,  2.3860e-01, -1.2429e-01, -6.6136e-02,  8.0275e-02,
           7.1631e-01,  1.8756e-01],
         [-1.1250e-01, -6.2817e-02, -2.3901e-01, -3.2487e-01, -6.6114e-01,
           1.2824e-01,  1.1865e-01],
         [ 3.6873e-01, -1.7484e-01, -8.9865e-01, -2.2652e-01, -2.8544e-01,
          -3.6522e-01,  7.2972e-01]],

        [[ 6.2852e-02, -8.3042e-01, -8.3662e-01, -1.0109e+00,  2.8049e-02,
           3.7138e-01,  1.0355e-01],
         [-1.1405e+00,  3.5362e-01,  5.8261e-02, -1.0858e+00,  2.0134e-01,
           2.2057e-02, -8.1646e-01],
         [-8.5904e-01,  1.0562e-01, -9.2299e-02, -6.5875e-01, -8.4991e-01,
           2.2436e-01, -1

In [16]:
hidden2

torch.return_types.max(
values=tensor([[ 0.2838,  0.2586,  0.6632],
        [ 0.7163,  0.1282,  0.7297],
        [ 0.3714,  0.3536,  0.2244],
        [ 1.5365,  0.4475,  0.9227],
        [ 1.6285,  0.0643,  0.3683],
        [ 0.7006,  0.5521, -0.1444],
        [ 1.3244,  0.3922,  0.6033],
        [ 1.4759,  0.1482,  1.5075],
        [ 1.3582,  0.2192,  0.3656],
        [ 0.5228, -0.1524,  0.4258],
        [ 1.0092,  0.4011,  0.8427],
        [ 2.0264, -0.0148,  1.0718],
        [ 0.0668,  0.0589,  0.5368],
        [ 1.5870,  0.6834,  0.7559],
        [ 0.7051,  0.3618,  0.1300],
        [ 0.1460,  0.3866,  0.4541]], grad_fn=<MaxBackward0>),
indices=tensor([[1, 5, 4],
        [5, 5, 6],
        [5, 1, 5],
        [4, 3, 3],
        [5, 4, 6],
        [1, 2, 2],
        [3, 2, 4],
        [4, 0, 5],
        [5, 4, 6],
        [6, 2, 1],
        [3, 0, 4],
        [2, 6, 3],
        [3, 2, 4],
        [5, 6, 4],
        [1, 4, 3],
        [0, 2, 6]]))

In [17]:
import pprint

In [18]:
pprint.pprint('''
[[[1, 11, 50, 42, 30, 43, 71, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], [1, 26, 37, 30, 49, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], [1, 33, 44, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], [1, 52, 34, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], [1, 52, 30, 43, 49, 70, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]], [[1, 6, 44, 42, 45, 50, 49, 34, 47, 71, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], [1, 17, 30, 49, 50, 47, 30, 41, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], [1, 41, 30, 43, 36, 50, 30, 36, 34, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], [1, 45, 47, 44, 32, 34, 48, 48, 38, 43, 36, 69, 2, 0, 0, 0, 0, 0, 0, 0, 0], [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]], [[1, 11, 50, 42, 30, 43, 71, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], [1, 26, 37, 34, 43, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], [1, 33, 44, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], [1, 52, 34, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], [1, 52, 30, 43, 49, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], [1, 38, 49, 70, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]], [[1, 6, 44, 42, 45, 50, 49, 34, 47, 71, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], [1, 26, 37, 34, 43, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], [1, 33, 44, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], [1, 52, 34, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], [1, 52, 30, 43, 49, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], [1, 52, 37, 30, 49, 70, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]]] but is:
[[[1, 11, 50, 42, 30, 43, 71, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], [1, 26, 37, 30, 49, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], [1, 33, 44, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], [1, 52, 34, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], [1, 52, 30, 43, 49, 70, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], 0], [[1, 6, 44, 42, 45, 50, 49, 34, 47, 71, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], [1, 17, 30, 49, 50, 47, 30, 41, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], [1, 41, 30, 43, 36, 50, 30, 36, 34, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], [1, 45, 47, 44, 32, 34, 48, 48, 38, 43, 36, 69, 2, 0, 0, 0, 0, 0, 0, 0, 0], 0, 0], [[1, 11, 50, 42, 30, 43, 71, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], [1, 26, 37, 34, 43, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], [1, 33, 44, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], [1, 52, 34, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], [1, 52, 30, 43, 49, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], [1, 38, 49, 70, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]], [[1, 6, 44, 42, 45, 50, 49, 34, 47, 71, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], [1, 26, 37, 34, 43, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], [1, 33, 44, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], [1, 52, 34, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], [1, 52, 30, 43, 49, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], [1, 52, 37, 30, 49, 70, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]]]

''')

('\n'
 '[[[1, 11, 50, 42, 30, 43, 71, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], [1, '
 '26, 37, 30, 49, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], [1, 33, 44, '
 '2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], [1, 52, 34, 2, 0, 0, '
 '0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], [1, 52, 30, 43, 49, 70, 2, 0, '
 '0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, '
 '0, 0, 0, 0, 0, 0, 0, 0, 0]], [[1, 6, 44, 42, 45, 50, 49, 34, 47, 71, 2, 0, '
 '0, 0, 0, 0, 0, 0, 0, 0, 0], [1, 17, 30, 49, 50, 47, 30, 41, 2, 0, 0, 0, 0, '
 '0, 0, 0, 0, 0, 0, 0, 0], [1, 41, 30, 43, 36, 50, 30, 36, 34, 2, 0, 0, 0, 0, '
 '0, 0, 0, 0, 0, 0, 0], [1, 45, 47, 44, 32, 34, 48, 48, 38, 43, 36, 69, 2, 0, '
 '0, 0, 0, 0, 0, 0, 0], [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, '
 '0, 0, 0], [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]], '
 '[[1, 11, 50, 42, 30, 43, 71, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], [1, '
 '26, 37, 34, 43, 2, 0, 0, 0, 0,

In [45]:
x = torch.randn(4,2,3)

In [46]:
x.permute(1,0,2)

tensor([[[ 0.6809,  1.4332,  0.6032],
         [-1.7336,  0.4938, -0.9024],
         [ 1.7072, -1.5668,  1.1772],
         [-0.9015, -0.0399, -0.5825]],

        [[-0.5831,  0.4928, -0.9836],
         [-0.4227, -0.4938,  0.4154],
         [-2.3309, -0.4504,  0.9891],
         [-1.1896,  0.4062, -1.0083]]])

In [47]:
x

tensor([[[ 0.6809,  1.4332,  0.6032],
         [-0.5831,  0.4928, -0.9836]],

        [[-1.7336,  0.4938, -0.9024],
         [-0.4227, -0.4938,  0.4154]],

        [[ 1.7072, -1.5668,  1.1772],
         [-2.3309, -0.4504,  0.9891]],

        [[-0.9015, -0.0399, -0.5825],
         [-1.1896,  0.4062, -1.0083]]])

In [49]:
sentence_length, batch_size, max_word_length = x.size()

In [51]:
[sentence_length1, batch_size1, max_word_length1] = list(x.size())

In [54]:
sentence_length == sentence_length1

True